export const INIT_MSG = {
  id: 1,
  username: '会务助手',
  msg: '欢迎各位参加"西湖论剑·安恒信息年度新品发布会"，直播即将开始！',
  avatar: 'https://i.pravatar.cc/150?img=1',
  isSelf: false,
};
export const SELF_MSG = { username: '范渊', avatar: '', isSelf: true };

export const MOCK_LIVE_CHAT = [
  {
    username: '网络安全李工',
    msg: '听说今天要发布新一代玄武盾，期待实战演示环节！',
    avatar: 'https://i.pravatar.cc/150?img=5',
    isSelf: false,
  },
  {
    username: '杭州张主任',
    msg: '范院士的《数据安全治理白皮书》什么时候可以下载？',
    avatar: 'https://i.pravatar.cc/150?img=11',
    isSelf: false,
  },
  {
    username: '会务助手',
    msg: '回复@杭州张主任：白皮书电子版将在茶歇后通过会议系统推送',
    avatar: 'https://i.pravatar.cc/150?img=1',
    isSelf: false,
  },
  {
    username: '开发者小王',
    msg: 'API安全网关的SDK会开源吗？求个GitHub地址',
    avatar: 'https://i.pravatar.cc/150?img=33',
    isSelf: false,
  },
  {
    username: '产品经理Alex',
    msg: '本次发布的AiLPHA大数据智能安全平台支持多租户模式了！',
    avatar: 'https://i.pravatar.cc/150?img=60',
    isSelf: false,
  },
  {
    username: '上海刘总',
    msg: '圆桌讨论能不能增加云安全合规的议题？',
    avatar: 'https://i.pravatar.cc/150?img=45',
    isSelf: false,
  },
  {
    username: '浙大学生代表',
    msg: '请问对高校网络安全人才培养有没有专项合作计划？',
    avatar: 'https://i.pravatar.cc/150?img=28',
    isSelf: false,
  },
  {
    username: '直播管理员',
    msg: '温馨提示：提问请注明单位+姓名，方便后续交流',
    avatar: 'https://i.pravatar.cc/150?img=3',
    isSelf: false,
  },
  {
    username: '金融陈总监',
    msg: '刚才演示的APT攻击溯源功能太强了，求产品手册',
    avatar: 'https://i.pravatar.cc/150?img=13',
    isSelf: false,
  },
  {
    username: '科技日报记者',
    msg: '请问本次发布的态势感知3.0相比竞品核心优势是什么？',
    avatar: 'https://i.pravatar.cc/150?img=68',
    isSelf: false,
  },
  {
    username: '运维老赵',
    msg: '告警误报率降低了多少？我们最关心这个',
    avatar: 'https://i.pravatar.cc/150?img=70',
    isSelf: false,
  },
  {
    username: '安恒技术专家',
    msg: '回复@运维老赵：通过AI模型优化，误报率下降67%，稍后有详细数据',
    avatar: 'https://i.pravatar.cc/150?img=40',
    isSelf: false,
  },
  {
    username: '投资人David',
    msg: '想了解威胁情报订阅服务的商业模式',
    avatar: 'https://i.pravatar.cc/150?img=22',
    isSelf: false,
  },
  {
    username: '医疗王主任',
    msg: '医疗数据脱敏方案有没有通过等保2.0认证？',
    avatar: 'https://i.pravatar.cc/150?img=51',
    isSelf: false,
  },
  {
    username: '直播管理员',
    msg: '抽奖环节即将开始，发送「安全+创新」参与抽奖',
    avatar: 'https://i.pravatar.cc/150?img=3',
    isSelf: false,
  },
  {
    username: '浙大实验室',
    msg: '期待下午的攻防演练直播，已准备好学习笔记！',
    avatar: 'https://i.pravatar.cc/150?img=8',
    isSelf: false,
  },
  {
    username: '阿里云代表',
    msg: '祝贺安恒发布新一代云安全解决方案！',
    avatar: 'https://i.pravatar.cc/150?img=53',
    isSelf: false,
  },
  {
    username: '公安张队长',
    msg: '这个攻击溯源系统能否对接公安大数据平台？',
    avatar: 'https://i.pravatar.cc/150?img=17',
    isSelf: false,
  },
  {
    username: 'CTF选手Tiger',
    msg: '新版本WAF的绕过难度提高了多少？求测试demo',
    avatar: 'https://i.pravatar.cc/150?img=29',
    isSelf: false,
  },
  {
    username: '能源周工',
    msg: '工业控制系统的安全防护方案有演示吗？',
    avatar: 'https://i.pravatar.cc/150?img=62',
    isSelf: false,
  },
  {
    username: '顾问Linda',
    msg: '这套方案在金融行业的落地案例有哪些？',
    avatar: 'https://i.pravatar.cc/150?img=39',
    isSelf: false,
  },
  {
    username: 'AI安全研究员',
    msg: 'AI模型安全检测功能支持哪些框架？',
    avatar: 'https://i.pravatar.cc/150?img=47',
    isSelf: false,
  },
  {
    username: '电信安全部',
    msg: '5G核心网的安全防护有专门解决方案吗？',
    avatar: 'https://i.pravatar.cc/150?img=19',
    isSelf: false,
  },
  {
    username: '漏洞猎手',
    msg: '漏洞奖励计划今年还会继续吗？',
    avatar: 'https://i.pravatar.cc/150?img=34',
    isSelf: false,
  },
  {
    username: '法律赵律师',
    msg: '数据跨境传输方案是否符合最新法规要求？',
    avatar: 'https://i.pravatar.cc/150?img=55',
    isSelf: false,
  },
  {
    username: '等保测评师',
    msg: '新平台是否预置了等保2.0的检查模板？',
    avatar: 'https://i.pravatar.cc/150?img=42',
    isSelf: false,
  },
  {
    username: '区块链专家',
    msg: '智能合约安全审计工具支持多链吗？',
    avatar: 'https://i.pravatar.cc/150?img=63',
    isSelf: false,
  },
  {
    username: '航空安全组',
    msg: '航空系统的威胁情报如何同步？',
    avatar: 'https://i.pravatar.cc/150?img=72',
    isSelf: false,
  },
  {
    username: '车联网安全',
    msg: '车载T-Box的安全防护方案有吗？',
    avatar: 'https://i.pravatar.cc/150?img=48',
    isSelf: false,
  },
  {
    username: 'IoT专家',
    msg: '物联网设备指纹识别准确率能达到多少？',
    avatar: 'https://i.pravatar.cc/150?img=57',
    isSelf: false,
  },
  {
    username: '密码学博士',
    msg: '后量子密码模块什么时候可以试用？',
    avatar: 'https://i.pravatar.cc/150?img=25',
    isSelf: false,
  },
  {
    username: 'SOC值班员',
    msg: '告警聚合功能能减少多少重复工单？',
    avatar: 'https://i.pravatar.cc/150?img=36',
    isSelf: false,
  },
  {
    username: '红队指挥官',
    msg: '攻击模拟的流量能否更贴近真实APT？',
    avatar: 'https://i.pravatar.cc/150?img=44',
    isSelf: false,
  },
  {
    username: '云架构师',
    msg: '多云环境的统一安全管理如何实现？',
    avatar: 'https://i.pravatar.cc/150?img=52',
    isSelf: false,
  },
  {
    username: '情报分析师',
    msg: '威胁情报的IOC更新频率是多少？',
    avatar: 'https://i.pravatar.cc/150?img=38',
    isSelf: false,
  },
  {
    username: 'FinTech安全',
    msg: '同态加密在支付场景的性能损耗多大？',
    avatar: 'https://i.pravatar.cc/150?img=65',
    isSelf: false,
  },
  {
    username: '护网观察员',
    msg: '今年的HW行动会有新攻击手法演示吗？',
    avatar: 'https://i.pravatar.cc/150?img=23',
    isSelf: false,
  },
  {
    username: '数据治理专家',
    msg: '敏感数据自动分类的准确率如何？',
    avatar: 'https://i.pravatar.cc/150?img=31',
    isSelf: false,
  },
  {
    username: '供应链安全',
    msg: '软件物料清单(SBOM)分析支持哪些格式？',
    avatar: 'https://i.pravatar.cc/150?img=59',
    isSelf: false,
  },
  {
    username: 'AI伦理委员',
    msg: '如何防止安全AI被滥用？',
    avatar: 'https://i.pravatar.cc/150?img=27',
    isSelf: false,
  },
  {
    username: '央企安全部',
    msg: '这套方案在集团型企业如何分级部署？',
    avatar: 'https://i.pravatar.cc/150?img=15',
    isSelf: false,
  },
  {
    username: '开源维护者',
    msg: '有没有计划开源部分检测规则？',
    avatar: 'https://i.pravatar.cc/150?img=49',
    isSelf: false,
  },
  {
    username: '取证专家',
    msg: '电子取证的时间戳如何保证不可篡改？',
    avatar: 'https://i.pravatar.cc/150?img=56',
    isSelf: false,
  },
  {
    username: '工业互联网',
    msg: 'PLC漏洞检测的误操作风险怎么控制？',
    avatar: 'https://i.pravatar.cc/150?img=64',
    isSelf: false,
  },
  {
    username: '隐私计算',
    msg: '联邦学习的安全通信开销优化了吗？',
    avatar: 'https://i.pravatar.cc/150?img=32',
    isSelf: false,
  },
  {
    username: '元宇宙安全',
    msg: '数字资产防盗方案支持NFT吗？',
    avatar: 'https://i.pravatar.cc/150?img=66',
    isSelf: false,
  },
  {
    username: '卫星通信',
    msg: '卫星链路的加密延迟问题解决了吗？',
    avatar: 'https://i.pravatar.cc/150?img=71',
    isSelf: false,
  },
  {
    username: '5G安全实验室',
    msg: '切片安全隔离有实测数据吗？',
    avatar: 'https://i.pravatar.cc/150?img=54',
    isSelf: false,
  },
  {
    username: '关基保护员',
    msg: '针对工控系统的0day漏洞如何防御？',
    avatar: 'https://i.pravatar.cc/150?img=43',
    isSelf: false,
  },
  {
    username: '零信任架构',
    msg: '动态权限调整的粒度能到多细？',
    avatar: 'https://i.pravatar.cc/150?img=58',
    isSelf: false,
  },
  {
    username: '量子加密',
    msg: '量子密钥分发的实际部署案例有吗？',
    avatar: 'https://i.pravatar.cc/150?img=24',
    isSelf: false,
  },
  {
    username: '会务助手',
    msg: '今日所有PPT资料将在会后24小时内发送至注册邮箱',
    avatar: 'https://i.pravatar.cc/150?img=1',
    isSelf: false,
  },
];
